### PR TITLE
common: cursor.Parse("123A") should not fail

### LINKED ISSUE #37: cursor.Parse() should treat EOF as empty member
when parsing a cursor string with empty member, ie:
`4743834931740803072A`
should be parse as a Cursor with empty Member field, currently Parse throws an `io.EOF` error.

I see there's a test case with `Member: " "` but that seems counter-intuitive

### PR DESCRIPTION
**Pull request by peterbourgon**
Fixes #37

/cc @beorn7

### CODE REVIEW

**Comment by grobie** [comment]
Should we just remove support for go1.2 and rebase? Happy to do that.

**Comment by peterbourgon** [comment]
Oh, wow, that's some old Travis config :) Let me update...

**Comment by grobie** [comment]
:+1:

**Comment by peterbourgon** [comment]
@beorn7 Over to you for the merge. I suspect 8c835b0 is explained by some random regression on tip.

**Comment by beorn7** [comment]
Thanks.

**Pull request merged**
